### PR TITLE
Set up project testing environment 

### PR DESCRIPTION
**Pull request by logankilpatrick**
Addresses #14 

See below for reference. 
https://julialang.github.io/Pkg.jl/v1/creating-packages/#Adding-tests-to-the-package-1

### CODE REVIEW

**Comment by zsunberg** [comment]
Make sure to change the dependencies so that it is clear that only julia >= 1.2 is supported, because test/Project.toml only works with 1.2 or greater

**Comment by logankilpatrick** [comment]
Won’t it default back to using the primary project/manifest file if it can’t use the test one?

**Comment by zsunberg** [comment]
Maybe, but I don't think we want the same information in two places. We should either use test/Project.toml or put everything in the Project.toml [extras]

**Comment by zsunberg** [comment]
This seems stale

**Pull request closed without merging**
